const assert = require('assert');
const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, '..', 'templates', 'Index.html'), 'utf8');
const trecho = html.slice(html.indexOf('function linkNovidade('), html.indexOf('function criarTurnoEl('));
const criar = new Function('document', trecho + '; return linkNovidade;')({createElement: () => ({})});
assert.strictEqual(criar('javascript:alert(1)'), null);
assert.strictEqual(criar('obsidian://open?path=nota'), null);
assert.strictEqual(criar('https://example.org', true), null);
assert.strictEqual(criar(undefined), null);
assert.strictEqual(criar(''), null);
assert.strictEqual(criar('https://store.steampowered.com/app/10/', false, 'Jogo — 50%').textContent, 'Jogo — 50%');
assert.strictEqual(criar('https://t.me/canal/123', false, '<b>Oferta</b>').textContent, '<b>Oferta</b>');
assert.strictEqual(criar('obsidian://open?path=Promocoes.md', true, 'Todas as promoções').textContent, 'Todas as promoções');
const noticia = criar('https://example.org/materia');
assert.strictEqual(noticia.href, 'https://example.org/materia');
assert.strictEqual(noticia.rel, 'noopener noreferrer');
assert.strictEqual(criar('obsidian://open?path=nota', true).textContent, 'Ver todas as novidades no Obsidian ↗');
assert.ok(html.indexOf('if (noticia) luna.appendChild(noticia)') < html.indexOf('luna.append(conteudo, copiar)'));
assert.ok(html.indexOf('if (nota) luna.appendChild(nota)') > html.indexOf('luna.append(conteudo, copiar)'));
console.log('ok');
